"""Initial migration

Revision ID: 219ba38d041b
Revises: 
Create Date: 2026-06-24 11:39:25.286238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219ba38d041b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('mfa_required', sa.Boolean(), nullable=True),
    sa.Column('mfa_success', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_user_id'), ['user_id'], unique=False)

    op.create_table('mfa_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('trusted_after', sa.DateTime(), nullable=True),
    sa.Column('created_from_ip', sa.String(length=45), nullable=True),
    sa.Column('created_from_device', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mfa_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_methods_user_id'), ['user_id'], unique=False)

    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('trusted_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('trusted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trusted_devices_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_trusted_devices_user_id'), ['user_id'], unique=False)

    op.create_table('mfa_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mfa_method_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('session_risk_score', sa.Integer(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mfa_method_id'], ['mfa_methods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mfa_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_mfa_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mfa_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_mfa_events_timestamp'))

    op.drop_table('mfa_events')
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trusted_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_trusted_devices_device_fingerprint'))

    op.drop_table('trusted_devices')
    with op.batch_alter_table('security_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_alerts_created_at'))

    op.drop_table('security_alerts')
    with op.batch_alter_table('mfa_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_methods_user_id'))

    op.drop_table('mfa_methods')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_login_events_device_fingerprint'))

    op.drop_table('login_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
