"""Add MSAL authentication fields

Revision ID: bd1983be119b
Revises: 219ba38d041b
Create Date: 2026-06-26 10:29:42.889235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1983be119b'
down_revision = '219ba38d041b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entra_user_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('auth_method', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_entra_user_id'), ['entra_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_entra_user_id'))
        batch_op.drop_column('auth_method')
        batch_op.drop_column('entra_user_id')

    # ### end Alembic commands ###
