"""Add Entra models for MFA detection

Revision ID: c34d5ec874d2
Revises: bd1983be119b
Create Date: 2026-06-29 13:01:34.293384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34d5ec874d2'
down_revision = 'bd1983be119b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entra_user_id', sa.String(length=100), nullable=False),
    sa.Column('user_principal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identity_entra_user_id'), ['entra_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_identity_user_principal_name'), ['user_principal_name'], unique=False)

    op.create_table('entra_signin_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microsoft_event_id', sa.String(length=100), nullable=False),
    sa.Column('entra_user_id', sa.String(length=100), nullable=False),
    sa.Column('user_principal_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('app_display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('mfa_required', sa.Boolean(), nullable=True),
    sa.Column('mfa_satisfied', sa.Boolean(), nullable=True),
    sa.Column('risk_level_aggregated', sa.String(length=50), nullable=True),
    sa.Column('risk_detail', sa.String(length=50), nullable=True),
    sa.Column('conditional_access_status', sa.String(length=50), nullable=True),
    sa.Column('local_risk_score', sa.Integer(), nullable=True),
    sa.Column('local_risk_level', sa.String(length=50), nullable=True),
    sa.Column('local_risk_reasons', sa.Text(), nullable=True),
    sa.Column('impossible_travel_detected', sa.Boolean(), nullable=True),
    sa.Column('required_travel_speed_mph', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entra_user_id'], ['user_identity.entra_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entra_signin_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entra_signin_event_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_signin_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_signin_event_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_signin_event_entra_user_id'), ['entra_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_signin_event_impossible_travel_detected'), ['impossible_travel_detected'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_signin_event_local_risk_score'), ['local_risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_signin_event_microsoft_event_id'), ['microsoft_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_entra_signin_event_user_principal_name'), ['user_principal_name'], unique=False)

    op.create_table('user_auth_method_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entra_user_id', sa.String(length=100), nullable=False),
    sa.Column('user_principal_name', sa.String(length=255), nullable=False),
    sa.Column('method_id', sa.String(length=100), nullable=True),
    sa.Column('method_type', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entra_user_id'], ['user_identity.entra_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_auth_method_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_auth_method_snapshot_entra_user_id'), ['entra_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_auth_method_snapshot_method_id'), ['method_id'], unique=True)

    op.create_table('user_risk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entra_user_id', sa.String(length=100), nullable=False),
    sa.Column('user_principal_name', sa.String(length=255), nullable=False),
    sa.Column('current_risk_score', sa.Integer(), nullable=True),
    sa.Column('current_risk_level', sa.String(length=50), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('last_risky_signin_at', sa.DateTime(), nullable=True),
    sa.Column('last_impossible_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_mfa_change_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entra_user_id'], ['user_identity.entra_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_risk_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_risk_state_current_risk_level'), ['current_risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_risk_state_current_risk_score'), ['current_risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_risk_state_entra_user_id'), ['entra_user_id'], unique=True)

    op.create_table('entra_mfa_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microsoft_event_id', sa.String(length=100), nullable=False),
    sa.Column('entra_user_id', sa.String(length=100), nullable=False),
    sa.Column('user_principal_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activity_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=True),
    sa.Column('method_type', sa.String(length=100), nullable=True),
    sa.Column('initiated_by', sa.String(length=255), nullable=True),
    sa.Column('target_user', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('risk_score_at_time', sa.Integer(), nullable=True),
    sa.Column('related_recent_signin_id', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entra_user_id'], ['user_identity.entra_user_id'], ),
    sa.ForeignKeyConstraint(['related_recent_signin_id'], ['entra_signin_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entra_mfa_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entra_mfa_event_activity_name'), ['activity_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_mfa_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_mfa_event_entra_user_id'), ['entra_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_mfa_event_microsoft_event_id'), ['microsoft_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_entra_mfa_event_user_principal_name'), ['user_principal_name'], unique=False)

    op.create_table('entra_security_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entra_user_id', sa.String(length=100), nullable=False),
    sa.Column('user_principal_name', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('related_signin_event_id', sa.Integer(), nullable=True),
    sa.Column('related_mfa_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entra_user_id'], ['user_identity.entra_user_id'], ),
    sa.ForeignKeyConstraint(['related_mfa_event_id'], ['entra_mfa_event.id'], ),
    sa.ForeignKeyConstraint(['related_signin_event_id'], ['entra_signin_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entra_security_alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entra_security_alert_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_security_alert_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_security_alert_entra_user_id'), ['entra_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_security_alert_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_security_alert_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_entra_security_alert_user_principal_name'), ['user_principal_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entra_security_alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entra_security_alert_user_principal_name'))
        batch_op.drop_index(batch_op.f('ix_entra_security_alert_status'))
        batch_op.drop_index(batch_op.f('ix_entra_security_alert_severity'))
        batch_op.drop_index(batch_op.f('ix_entra_security_alert_entra_user_id'))
        batch_op.drop_index(batch_op.f('ix_entra_security_alert_created_at'))
        batch_op.drop_index(batch_op.f('ix_entra_security_alert_alert_type'))

    op.drop_table('entra_security_alert')
    with op.batch_alter_table('entra_mfa_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entra_mfa_event_user_principal_name'))
        batch_op.drop_index(batch_op.f('ix_entra_mfa_event_microsoft_event_id'))
        batch_op.drop_index(batch_op.f('ix_entra_mfa_event_entra_user_id'))
        batch_op.drop_index(batch_op.f('ix_entra_mfa_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_entra_mfa_event_activity_name'))

    op.drop_table('entra_mfa_event')
    with op.batch_alter_table('user_risk_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_risk_state_entra_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_risk_state_current_risk_score'))
        batch_op.drop_index(batch_op.f('ix_user_risk_state_current_risk_level'))

    op.drop_table('user_risk_state')
    with op.batch_alter_table('user_auth_method_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_auth_method_snapshot_method_id'))
        batch_op.drop_index(batch_op.f('ix_user_auth_method_snapshot_entra_user_id'))

    op.drop_table('user_auth_method_snapshot')
    with op.batch_alter_table('entra_signin_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entra_signin_event_user_principal_name'))
        batch_op.drop_index(batch_op.f('ix_entra_signin_event_microsoft_event_id'))
        batch_op.drop_index(batch_op.f('ix_entra_signin_event_local_risk_score'))
        batch_op.drop_index(batch_op.f('ix_entra_signin_event_impossible_travel_detected'))
        batch_op.drop_index(batch_op.f('ix_entra_signin_event_entra_user_id'))
        batch_op.drop_index(batch_op.f('ix_entra_signin_event_device_id'))
        batch_op.drop_index(batch_op.f('ix_entra_signin_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_entra_signin_event_country'))

    op.drop_table('entra_signin_event')
    with op.batch_alter_table('user_identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identity_user_principal_name'))
        batch_op.drop_index(batch_op.f('ix_user_identity_entra_user_id'))

    op.drop_table('user_identity')
    # ### end Alembic commands ###
